### ISSUE TITLE
How to host a site with a public domain using Tailscale funnel?

### ISSUE THREAD

**Issue by kdevan** [tailscale/caddy-tailscale#23]
@willnorris I've been looking at your code for [your personal blog ](https://github.com/willnorris/willnorris.com) and it seems to me you're doing something like this:

1. Using your own https certificate as opposed to using the Caddy automated https like ts.net domains would use.
2. Using Tailscale Funnel to route traffic from your public domain to your Tailscale node.

I'm just making some assumptions here based on going through your code base which has been very helpful by the way so thank you for making that public :) I've done some experimenting of my own but have not quite been able to get this to work. I can see your [Caddy config](https://github.com/willnorris/willnorris.com/blob/main/etc/Caddyfile) and that is making sense to me. It shows that auto_https is turned off.

My questions are:

1. How does this look on the DNS of your domain?
2. How does this look in Tailscale admin?
3. Any other details that might be helpful that are not obvious from looking at Caddyfile and Dockerfile?

**Comment by willnorris** [comment]
Cool, I'm glad the source code for my site was helpful!  You've got it mostly right, but here's a few more notes.  My main site, willnorris.com, runs in a docker container on Fly.io.  No Tailscale for that, just really a pretty simple Caddy server with static pages output from Hugo.  You're right that I don't use Caddy https certificates, but that's because Fly takes care of that for me.  So my main DNS is just a simple A record pointing to the Fly.io IP address:

```
% dig +short willnorris.com
37.16.22.168
```

I use the caddy-tailscale plugin to have my caddy server join my tailnet using a pre-authorized, reusable, ephemeral key with `tag:www-proxy`.  Here's that key in the admin panel:

<img width="789" alt="Screenshot 2023-10-28 at 9 00 09 PM" src="https://github.com/tailscale/caddy-tailscale/assets/1112/f84436d4-61f1-4a3e-a0e6-375d960dec79">

I run two instances of my site in different regions, and my site is fairly low traffic so the instances don't stick around for a really long time.  So new ones are spinning up pretty regularly.  It takes a little while for the old ones to actually get cleaned up (24 hours I think?  I don't remember, but I keep meaning to fix this), so I see a bunch of old caddy devices on my machines page (note how only two are currently connected):

<img width="766" alt="Screenshot 2023-10-28 at 9 03 29 PM" src="https://github.com/tailscale/caddy-tailscale/assets/1112/b2821a93-3f6f-4384-b21b-0bb97922104d">

As you may have noted in my caddy config, I have a reverse proxy configured to send the `/-/` path to port 10000 on my host named samson:

```caddyfile
handle /-/* {
  uri replace /-/ /
  reverse_proxy http://samson.tail27e07.ts.net:10000 {
    transport tailscale
    header_up Host {upstream_hostport}
  }
}
```

This isn't actually using Tailscale Funnel, it's just a normal Tailscale connection between the caddy-tsnet node and my laptop (samson).  I just have it connecting to port 10000 which I'll typically forward to a development server on my laptop using tailscale serve:

```
tailscale serve --bg --http 10000 localhost:8080
```

(That's actually a future calling syntax that's coming soon, currently available in unstable builds).  The Tailscale ACL entry to allow that connection is:

```json
    {
      "action": "accept",
      "src": ["tag:www-proxy"],
      "dst": ["samson:10000"],
    },
```

For now, I just have samson:10000 serving some static text...

```
tailscale serve --bg --http 10000 text:"hello, from samson"
```

... which you might be able to see on https://willnorris.com/-/ if my laptop is awake when you visit it.

So I'm not running my whole website over Funnel or even with the caddy-tailscale plugin.  Just one path that I use occasionally for testing things.

**Comment by willnorris** [comment]
That said, you could trivially setup Caddy to reverse proxy an entire site rather than just a path.  But you still need that running on a public server somewhere.

Alternately, that's what Tailscale Funnel does for you so that you don't need to have a separate server anywhere.  You are just limited to the ts.net hostname.
